name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0              # fetch full history
          persist-credentials: true   # keep the GITHUB_TOKEN in the remote

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
          force_orphan: true          # create gh-pages as a fresh orphan branch
          allow_empty_commit: true    # push even if no changes detected
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
