name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the ENTIRE repo (full history needed to update gh-pages)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Deploy the public/ folder to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Uses the built-in GITHUB_TOKEN so no extra secrets required
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Folder containing your static site
          publish_dir: public
