# .github/workflows/gh-pages.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout with full history
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) (Optional) build step goes here if you need it
      # - name: Build site
      #   run: npm ci && npm run build

      # 3) Upload the **public/** folder as a Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      # 4) Deploy that artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
