name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false   # disable SSH auth

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Force HTTPS push URL so GITHUB_TOKEN works
          remote_url: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          publish_branch: gh-pages
          publish_dir: public
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
